name: tests

on: [push, pull_request]

jobs:
  node:
    runs-on: ubuntu-latest
    container:
      image: library/node
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Tests
      run: |
          node check_config.js
