name: Auto Pull Request development To main
on:
  push:
    branches:
      - development
jobs:
  autoPullRequestDevelopmentToMain:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Run the Action
      uses: devops-infra/action-pull-request@v0.4.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: main
        target_branch: development
        title: Update main
        body: "**Automated pull request**"
